name: Report an issue with Spotcast
description: Report an issue with Spotcast
labels:
  - bug
  - pending-triage
assignees:
  - fcusson
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
  - type: markdown
    attributes:
      value: |
        ⚠️ **Notice**: Spotcast is currently experiencing a known outage. See [#543](https://github.com/fondberg/spotcast/issues/543) for details.
  - type: checkboxes
    id: outage_ack
    attributes:
      label: Outage Acknowledgement
      description: Please confirm you've read and understood the above notice.
      options:
        - label: "I confirm that I have read issue #543 and this report is **not** related to the current outage."
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: textarea
    validations:
      required: true
    attributes:
      label: System Health details
      description: >
        Can be found in [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
  - type: input
    validations:
      required: true
    attributes:
      label: Spotcast Version
      description: >
        What version of spotcast are you running.

        [![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=spotcast)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      multiple: false
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Diagnostics information
      placeholder: "drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
      description: >-
        Enable `debug logs` for Spotcast ([Settings ⇒ Devices & services ⇒ Spotcast ⇒ Enable debug logging](https://my.home-assistant.io/redirect/integration/?domain=spotcast))

        [![Open your Home Assistant instance and show the Spotcast Integration](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=spotcast)

        If your issue is with installing Spotcast, please provide HACS `debug logs` ([Settings ⇒ Devices & services ⇒ HACS ⇒ Enable debug logging](https://my.home-assistant.io/redirect/integration/?domain=hacs))

        [![Open your Home Assistant instance and show the HACS Integration](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=HACS)

        Once enabled, reattempt the steps that lead to your issue and disable the `debug logs`. A file will be downloaded by your browser. <ins>drag-and-drop that file into the textbox below.</ins>

        **Providing Debug Logs generally allows pinpointing defects and thus resolving issues faster.**
  - type: textarea
    attributes:
      label: Example YAML snippet
      description: |
        If applicable, please provide an example piece of YAML that can help reproduce the problem.
        This can be from an automation, script, or scene.
      render: yaml
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below.
